travis:
  secure:
    BINSTAR_TOKEN: DFz38T0t9dhLJNDd0EknhscizRQa4X8q5K6mPVsQnlhChjrpMy5qEYu+nCJbTj85FJCmiSc+fDMHJJrI0H58px/urZpt+Lsui5AnZz0qK62xMIM2sdAGr1K6XoLj8YuuUE0XEcOB0DyaC0FBmn9fWWl7DkzKHyoOydNq4asSh3H2gs+qBYiEFqoCDHawrWmvEnp2JsiWD+Zc40zbiIJIiSxn9yNpg/POav9C5HEtZkrwI/y7fg1SupLfTSaEQ+k2xJteOgyhlB8S+u2cSyU/pGG/p5MTjnIoHBmLIDx2rnCCP+wd6O3yGioGQGFcxmUtljicMrt3b1NjSa6nQ1RQ6FrnUzDUF3pTDf8s2x0ENCWE4Ow0PF9O4IPDqrg5KWww6vLOQCBQx10Q1X11WZJs6AEbRJQ7VgE39L3WDkbl5P1Yc81+k1vBMNyt+8w6UwEh0+ZX3TUHCKkYZB+yuCl4vjJEfqbO7jefbkx9rxtgCaYZqRb9q9yskvoLp8fl3BGxCnjgpgTUoox+8FVevnue95z3WhqDLCGcZBsoq1ibfjZLoYQ8838xKJf+bhij3FTkLxx4wbCnf2cKUpBTSR8NsjwiLB8cqNNbrkZXPTPd9gVLSwLkv8FPglNGW3RMGzbK1k664onxaeISIT8VrrAO26jOOtnncGpuhDTHQxket+s=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
